#!/bin/bash
#
# Copyright (C) 2013 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

JAVAC_SOURCE=1.8
JAVAC_TARGET=1.8

${JAVAC} -source ${JAVAC_SOURCE} -target ${JAVAC_TARGET} Test.java
dx --dex --output=classes.dex *.class

art -classpath classes.dex Test 1>art.out.log 2>art.err.log
if [[ $? != 0 ]]; then
   cat art.err.log
fi
cat art.out.log
